# Generated by Django 4.1.5 on 2023-01-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="Preço"
                    ),
                ),
                (
                    "quantidade_disponivel",
                    models.IntegerField(verbose_name="Quantidade Estoque"),
                ),
            ],
        ),
    ]
